version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
      - "curl -O https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip"
      - "unzip terraform_0.12.26_linux_amd64.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - echo "Running init on `date`" 
      - terraform init
      - terraform validate
      - terraform plan
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'